### ISSUE TITLE
"1 package can be upgraded. Run 'apt list --upgradable' to see it" i am new user what can i do

### ISSUE THREAD

**Issue by rajendrasarumagar** [joaopauloschuler/k-neural-api#9]

**Comment by rajendrasarumagar** [comment]
![Uploading Screenshot_20220609-091238_Termux.jpg…]()

**Comment by joaopauloschuler** [comment]
This question is unrelated to this API. You may look further at: https://www.google.com/search?q=%22package+can+be+upgraded%22 .
